"""
Name: Nishanth
Description: dice simulator
Date: 26th April 2022
Time: 10:04 PM
"""

import random
# import turtle
from tkinter import * 

root = Tk()      
canvas = Canvas(root, width = 300, height = 300)      
canvas.pack()

# t=turtle.Screen()
# turtle.speed(10000)
# turtle.pensize(5)

x = random.randint(1,6)
# print(x)

# turtle.penup()
# turtle.goto(-300, 300)
# turtle.pendown()
# turtle.color('black')

# turtle.forward(600)
# turtle.right(90)
# turtle.forward(600)
# turtle.right(90)
# turtle.forward(600)
# turtle.right(90)
# turtle.forward(600)
# turtle.right(90)

if x ==1:
    # turtle.penup()
    # turtle.goto(0,0)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()
    img = PhotoImage(file="dice1.png")      
    canvas.create_image(20,20, anchor=NW, image=img)     
elif x==2: 
    # turtle.penup()
    # turtle.goto(-50, 5)
    # turtle.pendown()
    # turtle.color('black', 'black') 
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()
    # turtle.penup()
    # turtle.goto(50, 5)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()   
    img = PhotoImage(file="dice2.png")      
    canvas.create_image(20,20, anchor=NW, image=img)

elif x==3: 
    # turtle.penup()
    # turtle.goto(-100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black') 
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()
    # turtle.penup()
    # turtle.goto(100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()  
    # turtle.penup()
    # turtle.goto(0, -50)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()  
    img = PhotoImage(file="Dice 3.png")      
    canvas.create_image(20,20, anchor=NW, image=img)

elif x==4: 
    # turtle.penup()
    # turtle.goto(-100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black') 
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()

    # turtle.penup()
    # turtle.goto(100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill() 

    # turtle.penup()
    # turtle.goto(-100, -100)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()

    # turtle.penup()
    # turtle.goto(100, -100)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()
    img = PhotoImage(file="Dice 4.png")      
    canvas.create_image(20,20, anchor=NW, image=img)

elif x==5: 
    # turtle.penup()
    # turtle.goto(-100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black') 
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()

    # turtle.penup()
    # turtle.goto(100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill() 

    # turtle.penup()
    # turtle.goto(-100, -100)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()

    # turtle.penup()
    # turtle.goto(100, -100)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill() 

    # turtle.penup()
    # turtle.goto(0, 200)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()
    img = PhotoImage(file="Dice 5.png")      
    canvas.create_image(20,20, anchor=NW, image=img)   

elif x==6: 
    # turtle.penup()
    # turtle.goto(-100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black') 
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()

    # turtle.penup()
    # turtle.goto(100, 50)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill() 

    # turtle.penup()
    # turtle.goto(-100, -100)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()

    # turtle.penup()
    # turtle.goto(100, -100)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill() 

    # turtle.penup()
    # turtle.goto(-100, 200)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill()   

    # turtle.penup()
    # turtle.goto(100, 200)
    # turtle.pendown()
    # turtle.color('black', 'black')
    # turtle.begin_fill()
    # turtle.circle(45)
    # turtle.end_fill() 
    img = PhotoImage(file="Dice 6.png")      
    canvas.create_image(20,20, anchor=NW, image=img)    

# t.exitonclick()
mainloop() 